"""
Python DSP simulator for dsp-graph signal graphs.

Runs a per-sample Python loop that mirrors the C++ code generated by
compile.py, enabling prototyping, unit-testing, and correctness verification
without compilation.

Usage::

    from gen_dsp.graph.simulate import simulate, SimState, SimResult

Requires numpy (install via ``pip install gen-dsp[sim]``).
"""

from __future__ import annotations

import math
import operator
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any

try:
    import numpy as np
    from numpy.typing import NDArray
except ImportError as exc:
    msg = "numpy is required for simulation. Install with: pip install gen-dsp[sim]"
    raise ImportError(
        msg
    ) from exc

from gen_dsp.graph.compile import NAMED_CONSTANT_VALUES
from gen_dsp.graph.models import (
    ADSR,
    SVF,
    Accum,
    Allpass,
    BinOp,
    Biquad,
    Buffer,
    BufRead,
    BufSize,
    BufWrite,
    Change,
    Clamp,
    Compare,
    Constant,
    Counter,
    Cycle,
    DCBlock,
    DelayLine,
    DelayRead,
    DelayWrite,
    Delta,
    Elapsed,
    Fold,
    GateOut,
    GateRoute,
    Graph,
    History,
    Latch,
    Lookup,
    Mix,
    MulAccum,
    NamedConstant,
    Node,
    Noise,
    OnePole,
    Pass,
    Peek,
    Phasor,
    PulseOsc,
    RateDiv,
    SampleHold,
    SampleRate,
    SawOsc,
    Scale,
    Select,
    Selector,
    SinOsc,
    Slide,
    SmoothParam,
    Smoothstep,
    Splat,
    TriOsc,
    UnaryOp,
    Wave,
    Wrap,
)
from gen_dsp.graph.subgraph import expand_subgraphs
from gen_dsp.graph.toposort import toposort
from gen_dsp.graph.validate import validate_graph

_NOISE_SEED = np.uint32(123456789)
_DENORM_EPS = 1e-18
_TWO_PI = 2.0 * math.pi
_SVF_PI = 3.14159265

_BINOP_FUNCTIONS: dict[str, Callable[[float, float], float]] = {
    "add": operator.add,
    "sub": operator.sub,
    "mul": operator.mul,
    "div": lambda a, b: a / b if b != 0.0 else 0.0,
    "min": min,
    "max": max,
    "mod": lambda a, b: math.fmod(a, b) if b != 0.0 else 0.0,
    "pow": math.pow,
    "atan2": math.atan2,
    "hypot": math.hypot,
    "absdiff": lambda a, b: abs(a - b),
    "step": lambda a, b: 1.0 if a >= b else 0.0,
    "and": lambda a, b: 1.0 if (a != 0.0 and b != 0.0) else 0.0,
    "or": lambda a, b: 1.0 if (a != 0.0 or b != 0.0) else 0.0,
    "xor": lambda a, b: 1.0 if ((a != 0.0) != (b != 0.0)) else 0.0,
    "rsub": lambda a, b: b - a,
    "rdiv": lambda a, b: b / a if a != 0.0 else 0.0,
    "rmod": lambda a, b: math.fmod(b, a) if a != 0.0 else 0.0,
    "gtp": lambda a, b: a if a > b else 0.0,
    "ltp": lambda a, b: a if a < b else 0.0,
    "gtep": lambda a, b: a if a >= b else 0.0,
    "ltep": lambda a, b: a if a <= b else 0.0,
    "eqp": lambda a, b: a if a == b else 0.0,
    "neqp": lambda a, b: a if a != b else 0.0,
    "fastpow": math.pow,
}

_UNARY_FUNCTIONS: dict[str, Callable[[float, SimState], float]] = {
    "neg": lambda a, _state: -a,
    "sign": lambda a, _state: 1.0 if a > 0.0 else (-1.0 if a < 0.0 else 0.0),
    "sin": lambda a, _state: math.sin(a),
    "cos": lambda a, _state: math.cos(a),
    "tanh": lambda a, _state: math.tanh(a),
    "exp": lambda a, _state: math.exp(a),
    "log": lambda a, _state: math.log(a) if a > 0.0 else float("-inf"),
    "abs": lambda a, _state: abs(a),
    "sqrt": lambda a, _state: math.sqrt(a) if a >= 0.0 else 0.0,
    "floor": lambda a, _state: math.floor(a),
    "ceil": lambda a, _state: math.ceil(a),
    "round": lambda a, _state: float(round(a)),
    "atan": lambda a, _state: math.atan(a),
    "asin": lambda a, _state: math.asin(max(-1.0, min(1.0, a))),
    "acos": lambda a, _state: math.acos(max(-1.0, min(1.0, a))),
    "tan": lambda a, _state: math.tan(a),
    "sinh": lambda a, _state: math.sinh(a),
    "cosh": lambda a, _state: math.cosh(a),
    "asinh": lambda a, _state: math.asinh(a),
    "acosh": lambda a, _state: math.acosh(a) if a >= 1.0 else 0.0,
    "atanh": lambda a, _state: math.atanh(a) if -1.0 < a < 1.0 else 0.0,
    "exp2": lambda a, _state: math.pow(2.0, a),
    "log2": lambda a, _state: math.log2(a) if a > 0.0 else float("-inf"),
    "log10": lambda a, _state: math.log10(a) if a > 0.0 else float("-inf"),
    "fract": lambda a, _state: a - math.floor(a),
    "trunc": lambda a, _state: math.trunc(a),
    "not": lambda a, _state: 1.0 if a == 0.0 else 0.0,
    "bool": lambda a, _state: 0.0 if a == 0.0 else 1.0,
    "mtof": lambda a, _state: 440.0 * math.pow(2.0, (a - 69.0) / 12.0),
    "ftom": lambda a, _state: 69.0 + 12.0 * math.log2(max(a, 1e-10) / 440.0),
    "atodb": lambda a, _state: 20.0 * math.log10(max(a, 1e-10)),
    "dbtoa": lambda a, _state: math.pow(10.0, a / 20.0),
    "phasewrap": lambda a, _state: a - _TWO_PI * math.floor(a / _TWO_PI + 0.5),
    "degrees": lambda a, _state: a * (180.0 / math.pi),
    "radians": lambda a, _state: a * (math.pi / 180.0),
    "mstosamps": lambda a, _state: a * _state.sr / 1000.0,
    "sampstoms": lambda a, _state: a * 1000.0 / _state.sr,
    "t60": lambda a, _state: (
        math.exp(-6.9078 / (a * _state.sr)) if a * _state.sr != 0.0 else 0.0
    ),
    "t60time": lambda a, _state: (
        -6.9078 / (math.log(a) * _state.sr)
        if a > 0.0 and a != 1.0 and _state.sr != 0.0
        else 0.0
    ),
    "fixdenorm": lambda a, _state: 0.0 if abs(a) < _DENORM_EPS else a,
    "fixnan": lambda a, _state: 0.0 if math.isnan(a) else a,
    "isdenorm": lambda a, _state: 1.0 if (abs(a) < _DENORM_EPS and a != 0.0) else 0.0,
    "isnan": lambda a, _state: 1.0 if math.isnan(a) else 0.0,
    "fastsin": lambda a, _state: math.sin(a),
    "fastcos": lambda a, _state: math.cos(a),
    "fasttan": lambda a, _state: math.tan(a),
    "fastexp": lambda a, _state: math.exp(a),
}

_COMPARE_FUNCTIONS: dict[str, Callable[[float, float], float]] = {
    "gt": lambda a, b: 1.0 if a > b else 0.0,
    "lt": lambda a, b: 1.0 if a < b else 0.0,
    "gte": lambda a, b: 1.0 if a >= b else 0.0,
    "lte": lambda a, b: 1.0 if a <= b else 0.0,
    "eq": lambda a, b: 1.0 if a == b else 0.0,
    "neq": lambda a, b: 1.0 if a != b else 0.0,
}

_ADSR_ATTACK = 1
_ADSR_DECAY = 2
_ADSR_SUSTAIN = 3
_ADSR_RELEASE = 4


class SimState:
    """Holds all mutable state for a simulated DSP graph."""

    def __init__(self, graph: Graph, sample_rate: float = 0.0) -> None:
        """Build a simulation state for a graph."""
        graph = expand_subgraphs(graph)
        errors = validate_graph(graph)
        if errors:
            raise ValueError("Invalid graph: " + "; ".join(errors))

        self.graph = graph
        self.sr = sample_rate if sample_rate > 0.0 else graph.sample_rate
        self.sorted_nodes = toposort(graph)
        self.params: dict[str, float] = {p.name: p.default for p in graph.params}
        self.state: dict[str, Any] = {}
        self._init_state()

    def _init_state(self) -> None:
        """Initialize node state, mirroring compile.py:_emit_state_init."""
        for node in self.sorted_nodes:
            _prime_node_state(node, self.state, _init=True)

    def reset(self) -> None:
        """Reset all state to initial values, mirroring compile.py:_emit_state_reset."""
        self.params = {p.name: p.default for p in self.graph.params}
        for node in self.sorted_nodes:
            _prime_node_state(node, self.state, _init=False)

    def set_param(self, name: str, value: float) -> None:
        """Set a parameter value. Raises KeyError if name is unknown."""
        if name not in self.params:
            msg = f"Unknown param: '{name}'"
            raise KeyError(msg)
        self.params[name] = value

    def get_param(self, name: str) -> float:
        """Get current parameter value. Raises KeyError if name is unknown."""
        if name not in self.params:
            msg = f"Unknown param: '{name}'"
            raise KeyError(msg)
        return self.params[name]

    def set_buffer(self, buffer_id: str, data: NDArray[np.float32]) -> None:
        """Set buffer contents. Data is truncated/zero-padded to buffer size."""
        key = f"{buffer_id}.buf"
        if key not in self.state:
            msg = f"Unknown buffer: '{buffer_id}'"
            raise KeyError(msg)
        buf: NDArray[np.float32] = self.state[key]
        copy_len = min(len(data), len(buf))
        buf[:copy_len] = data[:copy_len]
        buf[copy_len:] = 0.0

    def get_buffer(self, buffer_id: str) -> NDArray[np.float32]:
        """Get a copy of buffer contents."""
        key = f"{buffer_id}.buf"
        if key not in self.state:
            msg = f"Unknown buffer: '{buffer_id}'"
            raise KeyError(msg)
        buf: NDArray[np.float32] = self.state[key]
        return buf.copy()

    def get_peek(self, peek_id: str) -> float:
        """Get the last value captured by a Peek node."""
        key = f"{peek_id}.value"
        if key not in self.state:
            msg = f"Unknown peek: '{peek_id}'"
            raise KeyError(msg)
        return float(self.state[key])


def _fill_buffer_data(node: Buffer, buf: NDArray[np.float32]) -> None:
    """Fill a buffer using its configured initialization strategy."""
    if node.fill == "sine":
        buf[:] = np.sin(
            2.0 * np.pi * np.arange(node.size, dtype=np.float32) / node.size
        ).astype(np.float32)
    else:
        buf[:] = 0.0


def _prime_history_state(node: History, state: dict[str, Any], *, _init: bool) -> None:
    state[node.id] = node.init


def _prime_delay_line_state(
    node: DelayLine,
    state: dict[str, Any],
    *,
    _init: bool,
) -> None:
    nid = node.id
    if _init:
        state[f"{nid}.buf"] = np.zeros(node.max_samples, dtype=np.float32)
        state[f"{nid}.len"] = node.max_samples
    else:
        buf = state[f"{nid}.buf"]
        buf[:] = 0.0
    state[f"{nid}.wr"] = 0


def _prime_phase_state(
    node: Phasor | SinOsc | TriOsc | SawOsc | PulseOsc,
    state: dict[str, Any],
    *,
    _init: bool,
) -> None:
    state[f"{node.id}.phase"] = 0.0


def _prime_noise_state(node: Noise, state: dict[str, Any], *, _init: bool) -> None:
    state[f"{node.id}.seed"] = _NOISE_SEED


def _prime_prev_state(
    node: Delta | Change | OnePole | SmoothParam | Slide,
    state: dict[str, Any],
    *,
    _init: bool,
) -> None:
    state[f"{node.id}.prev"] = 0.0


def _prime_biquad_state(
    node: Biquad | SVF,
    state: dict[str, Any],
    *,
    _init: bool,
) -> None:
    state[f"{node.id}.s1"] = 0.0
    state[f"{node.id}.s2"] = 0.0


def _prime_dcblock_state(
    node: DCBlock | Allpass,
    state: dict[str, Any],
    *,
    _init: bool,
) -> None:
    state[f"{node.id}.xprev"] = 0.0
    state[f"{node.id}.yprev"] = 0.0


def _prime_sample_hold_state(
    node: SampleHold | Latch,
    state: dict[str, Any],
    *,
    _init: bool,
) -> None:
    state[f"{node.id}.held"] = 0.0
    state[f"{node.id}.ptrig"] = 0.0


def _prime_accum_state(node: Accum, state: dict[str, Any], *, _init: bool) -> None:
    state[f"{node.id}.sum"] = 0.0


def _prime_counter_state(node: Counter, state: dict[str, Any], *, _init: bool) -> None:
    state[f"{node.id}.count"] = 0
    state[f"{node.id}.ptrig"] = 0.0


def _prime_elapsed_state(node: Elapsed, state: dict[str, Any], *, _init: bool) -> None:
    state[f"{node.id}.count"] = 0


def _prime_mul_accum_state(
    node: MulAccum,
    state: dict[str, Any],
    *,
    _init: bool,
) -> None:
    state[f"{node.id}.prod"] = 1.0


def _prime_rate_div_state(node: RateDiv, state: dict[str, Any], *, _init: bool) -> None:
    state[f"{node.id}.count"] = 0
    state[f"{node.id}.held"] = 0.0


def _prime_adsr_state(node: ADSR, state: dict[str, Any], *, _init: bool) -> None:
    state[f"{node.id}.phase"] = 0
    state[f"{node.id}.output"] = 0.0
    state[f"{node.id}.ptrig"] = 0.0


def _prime_peek_state(node: Peek, state: dict[str, Any], *, _init: bool) -> None:
    state[f"{node.id}.value"] = 0.0


def _prime_buffer_state(node: Buffer, state: dict[str, Any], *, _init: bool) -> None:
    buf = state.get(f"{node.id}.buf")
    if _init:
        buf = np.zeros(node.size, dtype=np.float32)
        _fill_buffer_data(node, buf)
        state[f"{node.id}.buf"] = buf
        state[f"{node.id}.len"] = node.size
        return
    _fill_buffer_data(node, buf)


_STATE_PRIME_HANDLERS: tuple[
    tuple[tuple[type[Node], ...], Callable[[Node, dict[str, Any], bool], None]],
    ...,
] = (
    ((History,), _prime_history_state),
    ((DelayLine,), _prime_delay_line_state),
    ((Phasor, SinOsc, TriOsc, SawOsc, PulseOsc), _prime_phase_state),
    ((Noise,), _prime_noise_state),
    ((Delta, Change, OnePole, SmoothParam, Slide), _prime_prev_state),
    ((Biquad, SVF), _prime_biquad_state),
    ((DCBlock, Allpass), _prime_dcblock_state),
    ((SampleHold, Latch), _prime_sample_hold_state),
    ((Accum,), _prime_accum_state),
    ((Counter,), _prime_counter_state),
    ((Elapsed,), _prime_elapsed_state),
    ((MulAccum,), _prime_mul_accum_state),
    ((RateDiv,), _prime_rate_div_state),
    ((ADSR,), _prime_adsr_state),
    ((Peek,), _prime_peek_state),
    ((Buffer,), _prime_buffer_state),
)


def _prime_node_state(node: Node, state: dict[str, Any], *, _init: bool) -> None:
    """Populate or reset the state for a node."""
    for node_types, handler in _STATE_PRIME_HANDLERS:
        if isinstance(node, node_types):
            handler(node, state, _init=_init)
            return


@dataclass
class SimResult:
    """Result of a simulation run."""

    outputs: dict[str, NDArray[np.float32]] = field(default_factory=dict)
    state: SimState = field(repr=False, default=None)  # type: ignore[assignment]


@dataclass
class _SimulationRun:
    state: SimState
    inputs: dict[str, NDArray[np.float32]] | None
    ctrl_sorted: list[Node]
    audio_sorted: list[Node]
    ctrl_interval: int
    ctrl_set: set[str]
    held_vals: dict[str, float]


def _resolve_simulation_inputs(
    state: SimState,
    inputs: dict[str, NDArray[np.float32]] | None,
    n_samples: int,
) -> tuple[int, set[str]]:
    """Validate inputs and infer the number of samples."""
    input_ids = {inp.id for inp in state.graph.inputs}
    if inputs:
        lengths = {len(arr) for arr in inputs.values()}
        for iid in inputs:
            if iid not in input_ids:
                msg = f"Unknown input: '{iid}'"
                raise ValueError(msg)
        if len(lengths) > 1:
            msg = f"Input arrays have mismatched lengths: {lengths}"
            raise ValueError(msg)
        inferred = lengths.pop() if lengths else 0
        if n_samples == 0:
            n_samples = inferred
        elif n_samples != inferred:
            msg = f"n_samples={n_samples} does not match input length {inferred}"
            raise ValueError(
                msg
            )
    elif n_samples == 0:
        msg = "n_samples required when no inputs are provided"
        raise ValueError(msg)

    if input_ids and (not inputs or set(inputs.keys()) != input_ids):
        provided = set(inputs.keys()) if inputs else set()
        missing = input_ids - provided
        if missing:
            msg = f"Missing inputs: {missing}"
            raise ValueError(msg)

    return n_samples, input_ids


def _build_sample_values(
    state: SimState,
    inputs: dict[str, NDArray[np.float32]] | None,
    sample_index: int,
) -> dict[str, float]:
    """Build the per-sample value map."""
    vals: dict[str, float] = {}
    if inputs:
        for iid, arr in inputs.items():
            vals[iid] = float(arr[sample_index])
    vals.update(state.params)
    vals["sr"] = state.sr
    for node in state.sorted_nodes:
        if isinstance(node, History):
            vals[node.id] = float(state.state[node.id])
    return vals


def _write_history_values(
    history_nodes: list[History],
    vals: dict[str, float],
    state: SimState,
) -> None:
    """Apply deferred history writes."""
    for h in history_nodes:
        state.state[h.id] = vals[h.input] if isinstance(h.input, str) else h.input


def _capture_control_values(
    ctrl_sorted: list[Node],
    vals: dict[str, float],
    held_vals: dict[str, float],
) -> None:
    """Capture control-rate values for later reuse."""
    for node in ctrl_sorted:
        if node.id in vals:
            held_vals[node.id] = vals[node.id]


def _apply_control_rate_nodes(
    ctrl_sorted: list[Node],
    vals: dict[str, float],
    state: SimState,
    history_nodes: list[History],
) -> None:
    """Compute control-rate nodes and flush their history writes."""
    for node in ctrl_sorted:
        _compute_node(node, vals, state, history_nodes)


def _apply_audio_rate_nodes(
    audio_sorted: list[Node],
    vals: dict[str, float],
    state: SimState,
    history_nodes: list[History],
) -> None:
    """Compute audio-rate nodes and flush their history writes."""
    for node in audio_sorted:
        _compute_node(node, vals, state, history_nodes)


def _simulate_sample(sample_index: int, run: _SimulationRun) -> dict[str, float]:
    """Simulate one sample and return the computed values."""
    vals = _build_sample_values(run.state, run.inputs, sample_index)
    is_ctrl_boundary = (
        run.ctrl_interval > 0 and run.ctrl_set and sample_index % run.ctrl_interval == 0
    )
    if run.ctrl_interval > 0 and run.ctrl_set and not is_ctrl_boundary:
        vals.update(run.held_vals)

    ctrl_history: list[History] = []
    if is_ctrl_boundary:
        _apply_control_rate_nodes(run.ctrl_sorted, vals, run.state, ctrl_history)
        _write_history_values(ctrl_history, vals, run.state)
        _capture_control_values(run.ctrl_sorted, vals, run.held_vals)

    audio_history: list[History] = []
    _apply_audio_rate_nodes(run.audio_sorted, vals, run.state, audio_history)
    _write_history_values(audio_history, vals, run.state)
    return vals


def _resolve_ref(ref: str | float, vals: dict[str, float]) -> float:
    """Resolve a symbolic reference to a float value."""
    if isinstance(ref, float):
        return ref
    return vals[ref]


def _compute_history(
    node: History,
    _vals: dict[str, float],
    _state: SimState,
    history_nodes: list[History],
) -> None:
    history_nodes.append(node)


def _compute_binop(
    node: BinOp,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    b = _resolve_ref(node.b, vals)
    op_fn = _BINOP_FUNCTIONS.get(node.op)
    if op_fn is not None:
        vals[node.id] = op_fn(a, b)


def _compute_unary(
    node: UnaryOp,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    op_fn = _UNARY_FUNCTIONS.get(node.op)
    if op_fn is not None:
        vals[node.id] = op_fn(a, state)


def _compute_clamp(
    node: Clamp,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    lo = _resolve_ref(node.lo, vals)
    hi = _resolve_ref(node.hi, vals)
    vals[node.id] = min(max(a, lo), hi)


def _compute_constant(
    node: Constant,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    vals[node.id] = node.value


def _compute_delay_line(
    node: DelayLine,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    pass


def _compute_delay_read(
    node: DelayRead,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    dl = node.delay
    tap = _resolve_ref(node.tap, vals)
    buf: NDArray[np.float32] = state.state[f"{dl}.buf"]
    length: int = state.state[f"{dl}.len"]
    wr: int = state.state[f"{dl}.wr"]
    if node.interp == "none":
        pos = (wr - int(tap)) % length
        vals[node.id] = float(buf[pos])
    elif node.interp == "linear":
        vals[node.id] = _interp_linear_delay(tap, buf, length, wr)
    elif node.interp == "cubic":
        vals[node.id] = _interp_cubic_delay(tap, buf, length, wr)


def _compute_delay_write(
    node: DelayWrite,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    dl = node.delay
    val = _resolve_ref(node.value, vals)
    buf = state.state[f"{dl}.buf"]
    wr = state.state[f"{dl}.wr"]
    length = state.state[f"{dl}.len"]
    buf[wr] = np.float32(val)
    state.state[f"{dl}.wr"] = (wr + 1) % length


def _compute_phasor(
    node: Phasor,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    freq = _resolve_ref(node.freq, vals)
    phase = state.state[f"{node.id}.phase"]
    vals[node.id] = phase
    phase += freq / state.sr
    if phase >= 1.0:
        phase -= 1.0
    state.state[f"{node.id}.phase"] = phase


def _compute_noise(
    node: Noise,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    seed = state.state[f"{node.id}.seed"]
    with np.errstate(over="ignore"):
        seed = np.uint32(np.uint32(seed) * np.uint32(1664525) + np.uint32(1013904223))
    state.state[f"{node.id}.seed"] = seed
    vals[node.id] = float(np.int32(seed)) / 2147483648.0


def _compute_compare(
    node: Compare,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    b = _resolve_ref(node.b, vals)
    op_fn = _COMPARE_FUNCTIONS.get(node.op)
    if op_fn is not None:
        vals[node.id] = op_fn(a, b)


def _compute_select(
    node: Select,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    cond = _resolve_ref(node.cond, vals)
    vals[node.id] = (
        _resolve_ref(node.a, vals) if cond > 0.0 else _resolve_ref(node.b, vals)
    )


def _compute_wrap(
    node: Wrap,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    lo = _resolve_ref(node.lo, vals)
    hi = _resolve_ref(node.hi, vals)
    rng = hi - lo
    raw = math.fmod(a - lo, rng)
    if raw < 0.0:
        raw += rng
    vals[node.id] = lo + raw


def _compute_fold(
    node: Fold,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    lo = _resolve_ref(node.lo, vals)
    hi = _resolve_ref(node.hi, vals)
    rng = hi - lo
    t = math.fmod(a - lo, 2.0 * rng)
    if t < 0.0:
        t += 2.0 * rng
    vals[node.id] = lo + t if t <= rng else hi - (t - rng)


def _compute_mix(
    node: Mix,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    a_v = _resolve_ref(node.a, vals)
    b_v = _resolve_ref(node.b, vals)
    t_v = _resolve_ref(node.t, vals)
    vals[node.id] = a_v + (b_v - a_v) * t_v


def _compute_delta_change(
    node: Delta | Change,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    prev = state.state[f"{node.id}.prev"]
    if isinstance(node, Delta):
        vals[node.id] = a - prev
    else:
        vals[node.id] = 1.0 if a != prev else 0.0
    state.state[f"{node.id}.prev"] = a


def _compute_biquad(
    node: Biquad,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    x = _resolve_ref(node.a, vals)
    b0 = _resolve_ref(node.b0, vals)
    b1 = _resolve_ref(node.b1, vals)
    b2 = _resolve_ref(node.b2, vals)
    a1 = _resolve_ref(node.a1, vals)
    a2 = _resolve_ref(node.a2, vals)
    s1 = state.state[f"{node.id}.s1"]
    s2 = state.state[f"{node.id}.s2"]
    y = b0 * x + s1
    state.state[f"{node.id}.s1"] = b1 * x - a1 * y + s2
    state.state[f"{node.id}.s2"] = b2 * x - a2 * y
    vals[node.id] = y


def _compute_svf(
    node: SVF,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    x = _resolve_ref(node.a, vals)
    freq = _resolve_ref(node.freq, vals)
    q = _resolve_ref(node.q, vals)
    sr = state.sr
    s1 = state.state[f"{node.id}.s1"]
    s2 = state.state[f"{node.id}.s2"]
    g = math.tan(_SVF_PI * freq / sr)
    k = 1.0 / q
    a1 = 1.0 / (1.0 + g * (g + k))
    a2 = g * a1
    a3 = g * a2
    v3 = x - s2
    v1 = a1 * s1 + a2 * v3
    v2 = s2 + a2 * s1 + a3 * v3
    state.state[f"{node.id}.s1"] = 2.0 * v1 - s1
    state.state[f"{node.id}.s2"] = 2.0 * v2 - s2
    if node.mode == "lp":
        vals[node.id] = v2
    elif node.mode == "hp":
        vals[node.id] = x - k * v1 - v2
    elif node.mode == "bp":
        vals[node.id] = v1
    elif node.mode == "notch":
        vals[node.id] = x - k * v1


def _compute_one_pole(
    node: OnePole,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    c = _resolve_ref(node.coeff, vals)
    prev = state.state[f"{node.id}.prev"]
    y = c * a + (1.0 - c) * prev
    state.state[f"{node.id}.prev"] = y
    vals[node.id] = y


def _compute_dcblock_allpass(
    node: DCBlock | Allpass,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    x = _resolve_ref(node.a, vals)
    c = 0.995 if isinstance(node, DCBlock) else _resolve_ref(node.coeff, vals)
    xprev = state.state[f"{node.id}.xprev"]
    yprev = state.state[f"{node.id}.yprev"]
    y = x - xprev + c * yprev if isinstance(node, DCBlock) else c * (x - yprev) + xprev
    state.state[f"{node.id}.xprev"] = x
    state.state[f"{node.id}.yprev"] = y
    vals[node.id] = y


def _compute_oscillator(
    node: SinOsc | TriOsc | SawOsc | PulseOsc,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    freq = _resolve_ref(node.freq, vals)
    phase = state.state[f"{node.id}.phase"]
    if isinstance(node, SinOsc):
        vals[node.id] = math.sin(_TWO_PI * phase)
    elif isinstance(node, TriOsc):
        vals[node.id] = 4.0 * abs(phase - 0.5) - 1.0
    elif isinstance(node, SawOsc):
        vals[node.id] = 2.0 * phase - 1.0
    elif isinstance(node, PulseOsc):
        width = _resolve_ref(node.width, vals)
        vals[node.id] = 1.0 if phase < width else -1.0
    phase += freq / state.sr
    if phase >= 1.0:
        phase -= 1.0
    state.state[f"{node.id}.phase"] = phase


def _compute_sample_hold_latch(
    node: SampleHold | Latch,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    t = _resolve_ref(node.trig, vals)
    ptrig = state.state[f"{node.id}.ptrig"]
    held = state.state[f"{node.id}.held"]
    if isinstance(node, SampleHold):
        if (ptrig <= 0.0 and t > 0.0) or (ptrig > 0.0 and t <= 0.0):
            held = a
    elif ptrig <= 0.0 and t > 0.0:
        held = a
    state.state[f"{node.id}.ptrig"] = t
    state.state[f"{node.id}.held"] = held
    vals[node.id] = held


def _compute_accum(
    node: Accum,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    incr = _resolve_ref(node.incr, vals)
    reset = _resolve_ref(node.reset, vals)
    s = state.state[f"{node.id}.sum"]
    if reset > 0.0:
        s = 0.0
    s += incr
    state.state[f"{node.id}.sum"] = s
    vals[node.id] = s


def _compute_counter(
    node: Counter,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    t = _resolve_ref(node.trig, vals)
    mx = _resolve_ref(node.max, vals)
    ptrig = state.state[f"{node.id}.ptrig"]
    count = state.state[f"{node.id}.count"]
    if ptrig <= 0.0 and t > 0.0:
        count += 1
        if count >= int(mx):
            count = 0
    state.state[f"{node.id}.ptrig"] = t
    state.state[f"{node.id}.count"] = count
    vals[node.id] = float(count)


def _compute_elapsed(
    node: Elapsed,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    count = state.state[f"{node.id}.count"]
    vals[node.id] = float(count)
    state.state[f"{node.id}.count"] = count + 1


def _compute_mul_accum(
    node: MulAccum,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    incr = _resolve_ref(node.incr, vals)
    reset = _resolve_ref(node.reset, vals)
    prod = state.state[f"{node.id}.prod"]
    if reset > 0.0:
        prod = 1.0
    prod *= incr
    state.state[f"{node.id}.prod"] = prod
    vals[node.id] = prod


def _compute_buffer(
    node: Buffer,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    pass


def _compute_buf_read(
    node: BufRead,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    buf_id = node.buffer
    idx = _resolve_ref(node.index, vals)
    buf = state.state[f"{buf_id}.buf"]
    buf_len: int = state.state[f"{buf_id}.len"]
    if node.interp == "none":
        ii = int(idx)
        ii = max(0, min(ii, buf_len - 1))
        vals[node.id] = float(buf[ii])
    elif node.interp == "linear":
        vals[node.id] = _interp_linear_buf(idx, buf, buf_len)
    elif node.interp == "cubic":
        vals[node.id] = _interp_cubic_buf(idx, buf, buf_len)


def _compute_buf_write(
    node: BufWrite,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    buf_id = node.buffer
    idx = _resolve_ref(node.index, vals)
    val = _resolve_ref(node.value, vals)
    buf = state.state[f"{buf_id}.buf"]
    buf_len = state.state[f"{buf_id}.len"]
    ii = int(idx)
    if 0 <= ii < buf_len:
        buf[ii] = np.float32(val)


def _compute_splat(
    node: Splat,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    buf_id = node.buffer
    idx = _resolve_ref(node.index, vals)
    val = _resolve_ref(node.value, vals)
    buf = state.state[f"{buf_id}.buf"]
    buf_len = state.state[f"{buf_id}.len"]
    ii = int(idx)
    if 0 <= ii < buf_len:
        buf[ii] += np.float32(val)


def _compute_buf_size(
    node: BufSize,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    vals[node.id] = float(state.state[f"{node.buffer}.len"])


def _compute_cycle(
    node: Cycle,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    buf_id = node.buffer
    phase = _resolve_ref(node.phase, vals)
    buf = state.state[f"{buf_id}.buf"]
    buf_len = state.state[f"{buf_id}.len"]
    p = phase - math.floor(phase)
    fidx = p * buf_len
    i0 = int(fidx) % buf_len
    frac = fidx - math.floor(fidx)
    i1 = (i0 + 1) % buf_len
    vals[node.id] = float(buf[i0]) + frac * (float(buf[i1]) - float(buf[i0]))


def _compute_wave(
    node: Wave,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    buf_id = node.buffer
    phase = _resolve_ref(node.phase, vals)
    buf = state.state[f"{buf_id}.buf"]
    blen: int = state.state[f"{buf_id}.len"]
    norm = (phase + 1.0) * 0.5
    fidx = norm * (blen - 1)
    fidx = max(0.0, min(fidx, float(blen - 1)))
    i0 = int(fidx)
    frac = fidx - float(i0)
    i1 = min(i0 + 1, blen - 1)
    vals[node.id] = float(buf[i0]) + frac * (float(buf[i1]) - float(buf[i0]))


def _compute_lookup(
    node: Lookup,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    buf_id = node.buffer
    idx = _resolve_ref(node.index, vals)
    buf = state.state[f"{buf_id}.buf"]
    llen: int = state.state[f"{buf_id}.len"]
    ci = max(0.0, min(idx, 1.0))
    fidx = ci * (llen - 1)
    i0 = int(fidx)
    frac = fidx - float(i0)
    i1 = min(i0 + 1, llen - 1)
    vals[node.id] = float(buf[i0]) + frac * (float(buf[i1]) - float(buf[i0]))


def _compute_rate_div(
    node: RateDiv,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    divisor = _resolve_ref(node.divisor, vals)
    count = state.state[f"{node.id}.count"]
    held = state.state[f"{node.id}.held"]
    if count == 0:
        held = a
    count += 1
    if count >= int(divisor):
        count = 0
    state.state[f"{node.id}.count"] = count
    state.state[f"{node.id}.held"] = held
    vals[node.id] = held


def _compute_scale(
    node: Scale,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    in_lo = _resolve_ref(node.in_lo, vals)
    in_hi = _resolve_ref(node.in_hi, vals)
    out_lo = _resolve_ref(node.out_lo, vals)
    out_hi = _resolve_ref(node.out_hi, vals)
    in_range = in_hi - in_lo
    out_range = out_hi - out_lo
    vals[node.id] = (
        out_lo + (a - in_lo) / in_range * out_range if in_range != 0.0 else out_lo
    )


def _compute_smooth_param_slide(
    node: SmoothParam | Slide,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    if isinstance(node, SmoothParam):
        c = _resolve_ref(node.coeff, vals)
        prev = state.state[f"{node.id}.prev"]
        y = (1.0 - c) * a + c * prev
    else:
        up = _resolve_ref(node.up, vals)
        down = _resolve_ref(node.down, vals)
        prev = state.state[f"{node.id}.prev"]
        s = max(1.0, up if a > prev else down)
        y = prev + (a - prev) / s
    state.state[f"{node.id}.prev"] = y
    vals[node.id] = y


def _compute_adsr(
    node: ADSR,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    gate_val = _resolve_ref(node.gate, vals)
    attack_ms = _resolve_ref(node.attack, vals)
    decay_ms = _resolve_ref(node.decay, vals)
    sustain_lvl = _resolve_ref(node.sustain, vals)
    release_ms = _resolve_ref(node.release, vals)
    phase = state.state[f"{node.id}.phase"]
    output = state.state[f"{node.id}.output"]
    ptrig = state.state[f"{node.id}.ptrig"]
    sr = state.sr
    if gate_val > 0.0 and ptrig <= 0.0:
        phase = _ADSR_ATTACK
    if gate_val <= 0.0 and ptrig > 0.0:
        phase = _ADSR_RELEASE
    ptrig = gate_val
    if phase == _ADSR_ATTACK:
        a_samps = max(attack_ms * sr * 0.001, 1.0)
        output += 1.0 / a_samps
        if output >= 1.0:
            output = 1.0
            phase = _ADSR_DECAY
    if phase == _ADSR_DECAY:
        d_samps = max(decay_ms * sr * 0.001, 1.0)
        output -= (1.0 - sustain_lvl) / d_samps
        if output <= sustain_lvl:
            output = sustain_lvl
            phase = _ADSR_SUSTAIN
    if phase == _ADSR_SUSTAIN:
        output = sustain_lvl
    if phase == _ADSR_RELEASE:
        r_samps = max(release_ms * sr * 0.001, 1.0)
        output -= 1.0 / r_samps
        if output <= 0.0:
            output = 0.0
            phase = 0
    state.state[f"{node.id}.phase"] = phase
    state.state[f"{node.id}.output"] = output
    state.state[f"{node.id}.ptrig"] = ptrig
    vals[node.id] = output


def _compute_peek(
    node: Peek,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    vals[node.id] = a
    state.state[f"{node.id}.value"] = a


def _compute_pass(
    node: Pass,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    vals[node.id] = _resolve_ref(node.a, vals)


def _compute_named_constant(
    node: NamedConstant,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    vals[node.id] = NAMED_CONSTANT_VALUES[node.op]


def _compute_sample_rate(
    node: SampleRate,
    vals: dict[str, float],
    state: SimState,
    _history_nodes: list[History],
) -> None:
    vals[node.id] = state.sr


def _compute_smoothstep(
    node: Smoothstep,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    a = _resolve_ref(node.a, vals)
    e0 = _resolve_ref(node.edge0, vals)
    e1 = _resolve_ref(node.edge1, vals)
    rng = e1 - e0
    t = min(max((a - e0) / rng if rng != 0.0 else 0.0, 0.0), 1.0)
    vals[node.id] = t * t * (3.0 - 2.0 * t)


def _compute_gate_route(
    node: GateRoute,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    idx = int(_resolve_ref(node.index, vals))
    idx = max(0, min(idx, node.count))
    vals[f"{node.id}._idx"] = idx
    vals[f"{node.id}._val"] = _resolve_ref(node.a, vals)


def _compute_gate_out(
    node: GateOut,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    idx = vals[f"{node.gate}._idx"]
    val = vals[f"{node.gate}._val"]
    vals[node.id] = val if idx == node.channel else 0.0


def _compute_selector(
    node: Selector,
    vals: dict[str, float],
    _state: SimState,
    _history_nodes: list[History],
) -> None:
    idx = int(_resolve_ref(node.index, vals))
    idx = max(0, min(idx, len(node.inputs)))
    vals[node.id] = _resolve_ref(node.inputs[idx - 1], vals) if idx > 0 else 0.0


_COMPUTE_HANDLERS: tuple[
    tuple[
        tuple[type[Node], ...],
        Callable[[Node, dict[str, float], SimState, list[History]], None],
    ],
    ...,
] = (
    ((History,), _compute_history),
    ((BinOp,), _compute_binop),
    ((UnaryOp,), _compute_unary),
    ((Clamp,), _compute_clamp),
    ((Constant,), _compute_constant),
    ((DelayLine,), _compute_delay_line),
    ((DelayRead,), _compute_delay_read),
    ((DelayWrite,), _compute_delay_write),
    ((Phasor,), _compute_phasor),
    ((Noise,), _compute_noise),
    ((Compare,), _compute_compare),
    ((Select,), _compute_select),
    ((Wrap,), _compute_wrap),
    ((Fold,), _compute_fold),
    ((Mix,), _compute_mix),
    ((Delta, Change), _compute_delta_change),
    ((Biquad,), _compute_biquad),
    ((SVF,), _compute_svf),
    ((OnePole,), _compute_one_pole),
    ((DCBlock, Allpass), _compute_dcblock_allpass),
    ((SinOsc, TriOsc, SawOsc, PulseOsc), _compute_oscillator),
    ((SampleHold, Latch), _compute_sample_hold_latch),
    ((Accum,), _compute_accum),
    ((Counter,), _compute_counter),
    ((Elapsed,), _compute_elapsed),
    ((MulAccum,), _compute_mul_accum),
    ((Buffer,), _compute_buffer),
    ((BufRead,), _compute_buf_read),
    ((BufWrite,), _compute_buf_write),
    ((Splat,), _compute_splat),
    ((BufSize,), _compute_buf_size),
    ((Cycle,), _compute_cycle),
    ((Wave,), _compute_wave),
    ((Lookup,), _compute_lookup),
    ((RateDiv,), _compute_rate_div),
    ((Scale,), _compute_scale),
    ((SmoothParam, Slide), _compute_smooth_param_slide),
    ((ADSR,), _compute_adsr),
    ((Peek,), _compute_peek),
    ((Pass,), _compute_pass),
    ((NamedConstant,), _compute_named_constant),
    ((SampleRate,), _compute_sample_rate),
    ((Smoothstep,), _compute_smoothstep),
    ((GateRoute,), _compute_gate_route),
    ((GateOut,), _compute_gate_out),
    ((Selector,), _compute_selector),
)


def _compute_node(
    node: Node,
    vals: dict[str, float],
    state: SimState,
    history_nodes: list[History],
) -> None:
    """Compute a single node and update values/state in-place."""
    for node_types, handler in _COMPUTE_HANDLERS:
        if isinstance(node, node_types):
            handler(node, vals, state, history_nodes)
            return


def simulate(
    graph: Graph,
    inputs: dict[str, NDArray[np.float32]] | None = None,
    n_samples: int = 0,
    state: SimState | None = None,
    **kwargs: object,
) -> SimResult:
    """
    Simulate a DSP graph in Python, returning output arrays and state.

    Args:
        graph: The DSP graph to simulate.
        inputs: Dict mapping audio input IDs to float32 arrays. All arrays
            must have the same length. May be None for generators.
        n_samples: Number of samples to process. Inferred from inputs if 0.
            Required for generators (no inputs).
        params: Optional param overrides (name -> value).
        state: Optional SimState to reuse across calls. Created if None.
        sample_rate: Sample rate override. Uses graph.sample_rate if 0.
        kwargs: Optional legacy keyword arguments (`params`, `sample_rate`).

    Returns:
        SimResult with output arrays and the (possibly new) SimState.

    Raises:
        ValueError: On invalid graph, mismatched input shapes, etc.

    """
    params = kwargs.pop("params", None)
    sample_rate = kwargs.pop("sample_rate", 0.0)
    if kwargs:
        unexpected = ", ".join(sorted(kwargs))
        msg = f"Unexpected keyword arguments: {unexpected}"
        raise TypeError(msg)

    if state is None:
        state = SimState(graph, sample_rate)

    if params:
        for name, value in params.items():
            state.set_param(name, value)

    n_samples, _input_ids = _resolve_simulation_inputs(state, inputs, n_samples)
    output_arrays: dict[str, NDArray[np.float32]] = {}
    for out in state.graph.outputs:
        output_arrays[out.id] = np.zeros(n_samples, dtype=np.float32)

    ctrl_interval = state.graph.control_interval
    ctrl_set = set(state.graph.control_nodes) if ctrl_interval > 0 else set()
    ctrl_sorted = [n for n in state.sorted_nodes if n.id in ctrl_set]
    audio_sorted = [n for n in state.sorted_nodes if n.id not in ctrl_set]
    held_vals: dict[str, float] = {}
    run = _SimulationRun(
        state=state,
        inputs=inputs,
        ctrl_sorted=ctrl_sorted,
        audio_sorted=audio_sorted,
        ctrl_interval=ctrl_interval,
        ctrl_set=ctrl_set,
        held_vals=held_vals,
    )

    for i in range(n_samples):
        vals = _simulate_sample(i, run)
        for out in state.graph.outputs:
            output_arrays[out.id][i] = np.float32(vals[out.source])

    return SimResult(outputs=output_arrays, state=state)


# ---------------------------------------------------------------------------
# Delay interpolation helpers
# ---------------------------------------------------------------------------


def _interp_linear_delay(
    tap: float,
    buf: NDArray[np.float32],
    length: int,
    wr: int,
) -> float:
    itap = int(tap)
    frac = tap - float(itap)
    i0 = (wr - itap) % length
    i1 = (wr - itap - 1) % length
    s0 = float(buf[i0])
    s1 = float(buf[i1])
    return s0 + frac * (s1 - s0)


def _interp_cubic_delay(
    tap: float,
    buf: NDArray[np.float32],
    length: int,
    wr: int,
) -> float:
    itap = int(tap)
    frac = tap - float(itap)
    i0 = (wr - itap) % length
    im1 = (i0 + 1) % length
    i1 = (wr - itap - 1) % length
    i2 = (wr - itap - 2) % length
    ym1 = float(buf[im1])
    y0 = float(buf[i0])
    y1 = float(buf[i1])
    y2 = float(buf[i2])
    c0 = y0
    c1 = 0.5 * (y1 - ym1)
    c2 = ym1 - 2.5 * y0 + 2.0 * y1 - 0.5 * y2
    c3 = 0.5 * (y2 - ym1) + 1.5 * (y0 - y1)
    return ((c3 * frac + c2) * frac + c1) * frac + c0


# ---------------------------------------------------------------------------
# Buffer interpolation helpers
# ---------------------------------------------------------------------------


def _clamp_buf_idx(idx: int, buf_len: int) -> int:
    if idx < 0:
        return 0
    if idx >= buf_len:
        return buf_len - 1
    return idx


def _interp_linear_buf(
    idx: float,
    buf: NDArray[np.float32],
    buf_len: int,
) -> float:
    i0 = int(idx)
    frac = idx - float(i0)
    i1 = i0 + 1
    i0 = _clamp_buf_idx(i0, buf_len)
    i1 = _clamp_buf_idx(i1, buf_len)
    s0 = float(buf[i0])
    s1 = float(buf[i1])
    return s0 + frac * (s1 - s0)


def _interp_cubic_buf(
    idx: float,
    buf: NDArray[np.float32],
    buf_len: int,
) -> float:
    i0 = int(idx)
    frac = idx - float(i0)
    im1 = _clamp_buf_idx(i0 - 1, buf_len)
    i0c = _clamp_buf_idx(i0, buf_len)
    i1 = _clamp_buf_idx(i0 + 1, buf_len)
    i2 = _clamp_buf_idx(i0 + 2, buf_len)
    ym1 = float(buf[im1])
    y0 = float(buf[i0c])
    y1 = float(buf[i1])
    y2 = float(buf[i2])
    c0 = y0
    c1 = 0.5 * (y1 - ym1)
    c2 = ym1 - 2.5 * y0 + 2.0 * y1 - 0.5 * y2
    c3 = 0.5 * (y2 - ym1) + 1.5 * (y0 - y1)
    return ((c3 * frac + c2) * frac + c1) * frac + c0
